"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hashBlock = exports.openBlock = exports.nowBlock = exports.createBlock = exports.deleteBlock = exports.removeBlock = exports.writeBlock = exports.readBlock = exports.updateBlock = exports.initBlock = void 0;
var block_buzz_1 = require("./buz/block.buzz");
Object.defineProperty(exports, "initBlock", { enumerable: true, get: function () { return block_buzz_1.initBlock; } });
var block_buzz_2 = require("./buz/block.buzz");
Object.defineProperty(exports, "updateBlock", { enumerable: true, get: function () { return block_buzz_2.updateBlock; } });
var block_buzz_3 = require("./buz/block.buzz");
Object.defineProperty(exports, "readBlock", { enumerable: true, get: function () { return block_buzz_3.readBlock; } });
var block_buzz_4 = require("./buz/block.buzz");
Object.defineProperty(exports, "writeBlock", { enumerable: true, get: function () { return block_buzz_4.writeBlock; } });
var block_buzz_5 = require("./buz/block.buzz");
Object.defineProperty(exports, "removeBlock", { enumerable: true, get: function () { return block_buzz_5.removeBlock; } });
var block_buzz_6 = require("./buz/block.buzz");
Object.defineProperty(exports, "deleteBlock", { enumerable: true, get: function () { return block_buzz_6.deleteBlock; } });
var block_buzz_7 = require("./buz/block.buzz");
Object.defineProperty(exports, "createBlock", { enumerable: true, get: function () { return block_buzz_7.createBlock; } });
var block_buzz_8 = require("./buz/block.buzz");
Object.defineProperty(exports, "nowBlock", { enumerable: true, get: function () { return block_buzz_8.nowBlock; } });
var block_buzz_9 = require("./buz/block.buzz");
Object.defineProperty(exports, "openBlock", { enumerable: true, get: function () { return block_buzz_9.openBlock; } });
var block_buzz_10 = require("./buz/block.buzz");
Object.defineProperty(exports, "hashBlock", { enumerable: true, get: function () { return block_buzz_10.hashBlock; } });
//# sourceMappingURL=block.buzzer.js.map